package com.nimidev.bankingledger.domain;

import com.fasterxml.jackson.annotation.*;
import com.vaadin.annotations.AutoGenerated;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

@Entity
@Getter
@Setter
@EntityListeners(AuditingEntityListener.class)
public class Account extends Audit implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long accountId;

    @Column(unique = true , nullable = false)
    private String accountNo;

    @Column(nullable = false)
    private double currentBalance;

    @ManyToOne
    @JoinColumn(name = "customerId")
    private Customer customer;

    @ManyToOne
    @JoinColumn(name = "bankBranchId")
    @JsonIgnore
    private BankBranch bankBranch;

    @OneToMany(mappedBy = "account")
    private List<Transaction> transactions;

    @ManyToOne
    @JoinColumn(name = "currencyId")
    private Currency currency;


}
